name: Mirror to Gitee China Mirror

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "build"
  mirror:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1
      - uses: spyoungtech/mirror-action@master
        with:
          REMOTE: 'https://gitee.com/ohmysh/ohmysh-mirror.git'
          GIT_USERNAME: wujiayi516wjy
          GIT_PASSWORD: ${{ secrets.GITEE_PASSWORD }}
